### PR TITLE
Improve typography

### PR DESCRIPTION
**Pull request by dreua**
Remove colons as suffix in headings

### CODE REVIEW

**Comment by nucleus-ffm** [comment]
Thank you for your pull request. We have had an internal discussion about this and we are not sure if removing the colons would improve the typography or not. Can you perhaps give us some more information as to why this would be an improvement?

**Comment by dreua** [comment]
I think the headlines are already visually distinctive (bold, bigger font...) and after headlines there is always a kind of list of multiple similar items (paragraphs typically, they don't have bullet points but still are a collection of multiples similar items). Therefore I don't think that it makes sense to end each heading everywhere with a colon. If the content under a heading consists solely of a bulleted list you can easily see that by the bullets and the heading is already visually prominent, no need to point that out with an additional colon. In regular text the colon serves as a connector between the previous statement and the following list. Headings however are already connected to whatever follows below them by definition.

Here is a random university style guide which tends to agree: https://www.k-state.edu/webservices/cms/best-practices/heading-ending-colon.html

I'm seeing increased usage of colon prefixes in headings but I believe that is due to lack of knowledge or care (similar to people mixing up we're and were or below and bellow etc.). If you look at professionally designed apps or pages you'll almost never find those colon suffixes in headings.

What are the arguments pro colon suffix?

All that being said, I thank you your work on this open source alternative and you are free to do whatever you chose, I just see stuff like that and in an attempt to make the open source world look more polished and visually pleasing (in my and I hope the majority of eyes) I open PRs like this :heart:

**Review by T1z3n — COMMENTED** [review]
Look's fine

**Comment by nucleus-ffm** [comment]
I have removed the colons in the new version of the app. Currently in the branch https://github.com/nucleus-ffm/foss_warn/tree/improveCAPParsing 
Thanks for the contribution. If you notice any other things that we can improve in the typography, please feel free to open an issue. 
I will close this pull request now as it has already been changed.

**Pull request closed without merging**
